import Footer from '@/components/sections/Footer';
import './globals.css'
import { Poppins } from 'next/font/google'
import Header from '@/components/sections/Header';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} text-neutral-500 bg-neutral-50 dark:bg-neutral-950`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
